org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_version=0.1.0+1.20.1
maven_group=net.sweenus
archives_name=simplymastery
enabled_platforms=fabric,forge

minecraft_version=1.20.1
architectury_api_version=9.2.14
fabric_loader_version=0.18.4
fabric_api_version=0.92.6+1.20.1
forge_version=1.20.1-47.4.9
yarn_mappings=1.20.1+build.10
fzz_config_version=0.7.6+1.20.1
kotlinforforge_version=4.11.0
tomlkt_version=0.3.7

simply_swords_version=1.70.1
simply_swords_fabric_file_id=8723373
simply_swords_forge_file_id=8723370
simply_tooltips_fabric_file_id=8715150
simply_tooltips_forge_file_id=8715158

